### Repaso de clase anterior
En la clase anterior vimos un nuevo paquete llamado pandas üêº que nos permiti√≥ leer archivos csv de una forma un poco mas amigable que el paquete `csv`

In [3]:
import pandas as pd #casi todo el mundo importa pandas as√≠

In [26]:
data = pd.read_csv('listings.csv.gz')

In [27]:
data.head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,23726706,https://www.airbnb.com/rooms/23726706,20220605131734,2022-06-05,Private room 20 minutes from Amsterdam + Break...,Cousy private room 20 min. from Amsterdam. Sh...,We live in a nice Cousy and clean house with e...,https://a0.muscache.com/pictures/eb6d6636-02d6...,122619127,https://www.airbnb.com/users/show/122619127,...,4.97,4.73,4.87,038469D9AA6BDF1142CE,t,1,0,1,0,1.53
1,35815036,https://www.airbnb.com/rooms/35815036,20220605131734,2022-06-05,"Vrijstaand vakantiehuis, priv√© tuin aan het water",Bij het pittoreske dorpje Watergang ligt ons p...,U heeft hier diverse mogelijkheden. Zo kunt u ...,https://a0.muscache.com/pictures/e309d415-78de...,269425139,https://www.airbnb.com/users/show/269425139,...,4.98,4.81,4.83,NaN,f,1,1,0,0,2.65
2,31553121,https://www.airbnb.com/rooms/31553121,20220605131734,2022-06-05,Quiet Guesthouse near Amsterdam,Welcome to the countryside north of Amsterdam ...,Within 6 kilometers of the city center you'll ...,https://a0.muscache.com/pictures/64edc273-3b2b...,76806621,https://www.airbnb.com/users/show/76806621,...,4.95,4.62,4.59,NaN,f,1,1,0,0,2.02
3,34745823,https://www.airbnb.com/rooms/34745823,20220605131734,2022-06-05,"Apartment ' Landzicht', nearby Amsterdam","Apartment 'Landzicht', one of our three apartm...",Beautiful apartment 'Landzicht‚Äô located at a b...,https://a0.muscache.com/pictures/ceaafefc-7ccd...,238083700,https://www.airbnb.com/users/show/238083700,...,4.97,4.87,4.90,NaN,f,3,3,0,0,1.08
4,44586947,https://www.airbnb.com/rooms/44586947,20220605131734,2022-06-05,"Weesp, 2 kamers vlakbij Amsterdam",Ruime woning met 2 slaapkamers. 1 slaapkamer m...,Woning is gelegen in een gezellige nieuwbouwwi...,https://a0.muscache.com/pictures/6460aaa6-83df...,360838688,https://www.airbnb.com/users/show/360838688,...,4.93,5.00,4.80,NaN,f,1,0,1,0,0.68

Vamos a ver c√≥mo calculamos el precio promedio de los listings? y por barrio?

In [30]:
data_2 = pd.read_csv('listings.csv')
data_2['price'].mean()
#con el listing completo no anda, con el listing corto si.

198.01960149036125

In [32]:
data_2[data_2['neighbourhood']=='Bijlmer-Centrum']['price'].mean()

142.5731707317073

## Manipulaci√≥n de DFs y Series

### Operadores
Veamos que operaciones podemos aplicarle a una Serie de pandas

In [33]:
import numpy as np

In [34]:
df = pd.DataFrame(index = list(range(10)), columns = ['a', 'b', 'c'])
df['a'] = np.random.rand(10,1)
df['b'] = 1
df['c'] = np.random.rand(10,1)
df

          a  b         c
0  0.158055  1  0.109705
1  0.709789  1  0.194343
2  0.572891  1  0.733701
3  0.054267  1  0.747775
4  0.727996  1  0.235818
5  0.145281  1  0.480853
6  0.972191  1  0.140046
7  0.784969  1  0.910078
8  0.309619  1  0.638145
9  0.615481  1  0.426317

In [35]:
# np.random.rand?
#explorar la ayuda

In [36]:
# suma
df['a'] + df['b']

0    1.158055
1    1.709789
2    1.572891
3    1.054267
4    1.727996
5    1.145281
6    1.972191
7    1.784969
8    1.309619
9    1.615481
dtype: float64

In [37]:
df['d'] = df['a'] + df['b']
df

          a  b         c         d
0  0.158055  1  0.109705  1.158055
1  0.709789  1  0.194343  1.709789
2  0.572891  1  0.733701  1.572891
3  0.054267  1  0.747775  1.054267
4  0.727996  1  0.235818  1.727996
5  0.145281  1  0.480853  1.145281
6  0.972191  1  0.140046  1.972191
7  0.784969  1  0.910078  1.784969
8  0.309619  1  0.638145  1.309619
9  0.615481  1  0.426317  1.615481

In [38]:
# resta
df['a'] - df['b']

0   -0.841945
1   -0.290211
2   -0.427109
3   -0.945733
4   -0.272004
5   -0.854719
6   -0.027809
7   -0.215031
8   -0.690381
9   -0.384519
dtype: float64

In [39]:
# multiplicaci√≥n
df['a'] * df['b']

0    0.158055
1    0.709789
2    0.572891
3    0.054267
4    0.727996
5    0.145281
6    0.972191
7    0.784969
8    0.309619
9    0.615481
dtype: float64

### Valor nulo
Muchas veces, los datos que tenemos presentan valores nulos, NaNs.

In [40]:
df.loc[10, 'a'] = 2
df

           a    b         c         d
0   0.158055  1.0  0.109705  1.158055
1   0.709789  1.0  0.194343  1.709789
2   0.572891  1.0  0.733701  1.572891
3   0.054267  1.0  0.747775  1.054267
4   0.727996  1.0  0.235818  1.727996
5   0.145281  1.0  0.480853  1.145281
6   0.972191  1.0  0.140046  1.972191
7   0.784969  1.0  0.910078  1.784969
8   0.309619  1.0  0.638145  1.309619
9   0.615481  1.0  0.426317  1.615481
10  2.000000  NaN       NaN       NaN

In [41]:
# veamos que pasa cuando recalculamos la columna d
df['d'] = df['a'] + df['b']
df

           a    b         c         d
0   0.158055  1.0  0.109705  1.158055
1   0.709789  1.0  0.194343  1.709789
2   0.572891  1.0  0.733701  1.572891
3   0.054267  1.0  0.747775  1.054267
4   0.727996  1.0  0.235818  1.727996
5   0.145281  1.0  0.480853  1.145281
6   0.972191  1.0  0.140046  1.972191
7   0.784969  1.0  0.910078  1.784969
8   0.309619  1.0  0.638145  1.309619
9   0.615481  1.0  0.426317  1.615481
10  2.000000  NaN       NaN       NaN

Cuando queremos sumar dos celdas en la que una hay un valor nulo el resultado es otro valor nulo. Esto tiene sentido ya que pandas no sabe como sumar un valor nulo con un valor no nulo. 

Todos estamos tentados de reemplazar ese valor nulo por un cero, no? Pero c√≥mo sabemos si est√° bien reemplazarlo por un cero o por un -1 o por un 10? La respuesta es que depende del contexto del trabajo que estemos haciendo. 

Supongamos que en este trabajo tiene sentido reemplazar el valor nulo por un 0. Tenemos varias formas de hacer eso:
- reemplazar el NaN por un zero inplace
- reemplazar el NaN por un zero solo para la operaci√≥n en cuesti√≥n

In [42]:
df['a'] + df['b'].fillna(0)

0     1.158055
1     1.709789
2     1.572891
3     1.054267
4     1.727996
5     1.145281
6     1.972191
7     1.784969
8     1.309619
9     1.615481
10    2.000000
dtype: float64

In [43]:
df['a'].add(df['b'], fill_value = 0)

0     1.158055
1     1.709789
2     1.572891
3     1.054267
4     1.727996
5     1.145281
6     1.972191
7     1.784969
8     1.309619
9     1.615481
10    2.000000
dtype: float64

In [44]:
df['b'].fillna(0, inplace = True)
df['b']

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    0.0
Name: b, dtype: float64

### Alineaci√≥n de √≠ndices
Cuando operamos con dos series, pandas alinea los indices antes de realizar la operaci√≥n. 
Antes de realizar la operaci√≥n tenemos que tener en cuenta que:
- los √≠ndices sean √∫nicos
- los √≠ndices sean comunes a las dos series

Sino, van a obtener valores nulos o un resultado erroneo
![image.png]()


(Harrison, 2021)

### Filtrar Series y Dataframes
Muchas veces no queremos ver/usar todos los datos dentro del DF/Series y preferimos filtrarlos. 
Para eso generamos una Serie de booleanos que nos van a indicar si el √≠ndice en cuesti√≥n debe mostrarse o no. 

Veamos un ejemplo donde solo queremos ver aquellos registros donde el `review_scores_value` es mayor a 3

In [45]:
filtro = data['review_scores_value']>3
filtro

0        True
1        True
2        True
3        True
4        True
        ...
6168     True
6169     True
6170    False
6171     True
6172     True
Name: review_scores_value, Length: 6173, dtype: bool

In [46]:
data

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,23726706,https://www.airbnb.com/rooms/23726706,20220605131734,2022-06-05,Private room 20 minutes from Amsterdam + Break...,Cousy private room 20 min. from Amsterdam. Sh...,We live in a nice Cousy and clean house with e...,https://a0.muscache.com/pictures/eb6d6636-02d6...,122619127,https://www.airbnb.com/users/show/122619127,...,4.97,4.73,4.87,038469D9AA6BDF1142CE,t,1,0,1,0,1.53
1,35815036,https://www.airbnb.com/rooms/35815036,20220605131734,2022-06-05,"Vrijstaand vakantiehuis, priv√© tuin aan het water",Bij het pittoreske dorpje Watergang ligt ons p...,U heeft hier diverse mogelijkheden. Zo kunt u ...,https://a0.muscache.com/pictures/e309d415-78de...,269425139,https://www.airbnb.com/users/show/269425139,...,4.98,4.81,4.83,NaN,f,1,1,0,0,2.65
2,31553121,https://www.airbnb.com/rooms/31553121,20220605131734,2022-06-05,Quiet Guesthouse near Amsterdam,Welcome to the countryside north of Amsterdam ...,Within 6 kilometers of the city center you'll ...,https://a0.muscache.com/pictures/64edc273-3b2b...,76806621,https://www.airbnb.com/users/show/76806621,...,4.95,4.62,4.59,NaN,f,1,1,0,0,2.02
3,34745823,https://www.airbnb.com/rooms/34745823,20220605131734,2022-06-05,"Apartment ' Landzicht', nearby Amsterdam","Apartment 'Landzicht', one of our three apartm...",Beautiful apartment 'Landzicht‚Äô located at a b...,https://a0.muscache.com/pictures/ceaafefc-7ccd...,238083700,https://www.airbnb.com/users/show/238083700,...,4.97,4.87,4.90,NaN,f,3,3,0,0,1.08
4,44586947,https://www.airbnb.com/rooms/44586947,20220605131734,2022-06-05,"Weesp, 2 kamers vlakbij Amsterdam",Ruime woning met 2 slaapkamers. 1 slaapkamer m...,Woning is gelegen in een gezellige nieuwbouwwi...,https://a0.muscache.com/pictures/6460aaa6-83df...,360838688,https://www.airbnb.com/users/show/360838688,...,4.93,5.00,4.80,NaN,f,1,0,1,0,0.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6168,48005583,https://www.airbnb.com/rooms/48005583,20220605131734,2022-06-05,Aparthotel Adagio I Studio,The Studio is a perfect choice for anyone who ...,Adagio Amsterdam City South is situated in the...,https://a0.muscache.com/pictures/bc6ddb00-1074...,384216171,https://www.airbnb.com/users/show/384216171,...,4.50,4.50,4.50,NaN,t,5,5,0,0,0.77
6169,29532926,https://www.airbnb.com/rooms/29532926,20220605131734,2022-06-05,Cozy apartment close to Amsterdam,This is a cosy apartment only 10 minutes away ...,Diemen is very close to Amsterdam. In Diemen t...,https://a0.muscache.com/pictures/4497c610-3ae5...,222378910,https://www.airbnb.com/users/show/222378910,...,4.90,4.63,4.72,0384 1A62 6181 878C C2AB,f,1,1,0,0,2.64
6170,35760705,https://www.airbnb.com/rooms/35760705,20220605131734,2022-06-05,Modern Family House with Large Garden - Amste...,"A modern family house, located on the border o...",Situated less than a kilometer from Amsterdam ...,https://a0.muscache.com/pictures/197ca10f-aa6d...,54382559,https://www.airbnb.com/users/show/54382559,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
6171,36900951,https://www.airbnb.com/rooms/36900951,20220605131734,2022-06-05,House with big sunny garden in Amsterdam/A'veen,"Beautiful, family-friendly (ground floor) appa...","Nice quiet neighbourhood, restaurant, snackbar...",https://a0.muscache.com/pictures/19d54b17-3264...,35410939,https://www.airbnb.com/users/show/35410939,...,5.00,4.67,4.75,NaN,f,1,1,0,0,0.35
6172,40575103,https://www.airbnb.com/rooms/40575103,20220605131734,2022-06-05,"Priv√©kamer met badkamer, incl. ontbijt en park...",Ruime kamer met een eigen badkamer en toilet. ...,Mijn huis ligt in een rustige buurt. Het is st...,https://a0.muscache.com/pictures/bb805cc6-2391...,314410560,https://www.airbnb.com/users/show/314410560,...,5.00,4.62,4.76,0384 9B34 0EA9 5CC8 DC7F,t,1,0,1,0,0.96

In [47]:
len(data), len(data[filtro])

(6173, 5550)

In [48]:
data[filtro].head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,23726706,https://www.airbnb.com/rooms/23726706,20220605131734,2022-06-05,Private room 20 minutes from Amsterdam + Break...,Cousy private room 20 min. from Amsterdam. Sh...,We live in a nice Cousy and clean house with e...,https://a0.muscache.com/pictures/eb6d6636-02d6...,122619127,https://www.airbnb.com/users/show/122619127,...,4.97,4.73,4.87,038469D9AA6BDF1142CE,t,1,0,1,0,1.53
1,35815036,https://www.airbnb.com/rooms/35815036,20220605131734,2022-06-05,"Vrijstaand vakantiehuis, priv√© tuin aan het water",Bij het pittoreske dorpje Watergang ligt ons p...,U heeft hier diverse mogelijkheden. Zo kunt u ...,https://a0.muscache.com/pictures/e309d415-78de...,269425139,https://www.airbnb.com/users/show/269425139,...,4.98,4.81,4.83,NaN,f,1,1,0,0,2.65
2,31553121,https://www.airbnb.com/rooms/31553121,20220605131734,2022-06-05,Quiet Guesthouse near Amsterdam,Welcome to the countryside north of Amsterdam ...,Within 6 kilometers of the city center you'll ...,https://a0.muscache.com/pictures/64edc273-3b2b...,76806621,https://www.airbnb.com/users/show/76806621,...,4.95,4.62,4.59,NaN,f,1,1,0,0,2.02
3,34745823,https://www.airbnb.com/rooms/34745823,20220605131734,2022-06-05,"Apartment ' Landzicht', nearby Amsterdam","Apartment 'Landzicht', one of our three apartm...",Beautiful apartment 'Landzicht‚Äô located at a b...,https://a0.muscache.com/pictures/ceaafefc-7ccd...,238083700,https://www.airbnb.com/users/show/238083700,...,4.97,4.87,4.90,NaN,f,3,3,0,0,1.08
4,44586947,https://www.airbnb.com/rooms/44586947,20220605131734,2022-06-05,"Weesp, 2 kamers vlakbij Amsterdam",Ruime woning met 2 slaapkamers. 1 slaapkamer m...,Woning is gelegen in een gezellige nieuwbouwwi...,https://a0.muscache.com/pictures/6460aaa6-83df...,360838688,https://www.airbnb.com/users/show/360838688,...,4.93,5.00,4.80,NaN,f,1,0,1,0,0.68

#### Filtro usando cadenas
Supongamos que queremos filtrar todos los listings que tienen la palabra gato/cat en su descripci√≥n porque alguien del grupo de turistas es alergico/a a los üê±üê±üê±üê±üê±


La columna `description` tiene algunos elementos con valores nulos y no nos permite usar filtros. Por lo tanto, vamos a rellenar esos NaNs con alg√∫n valor que creamos acorde. Cuando trabajamos con cadenas, es com√∫n rellenar los NaNs con un espacio

In [49]:
data[data['description'].str.contains(' cat ')]

ValueError: ignored

In [50]:
data['description'].fillna(' ', inplace = True)

In [51]:
data[data['description'].str.contains(' cat ')].head(2)

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
17,50472290,https://www.airbnb.com/rooms/50472290,20220605131734,2022-06-05,2 bedroom rental unit in Amsterdam with garden,Nice 2 bedrome flat on the ground floor in pea...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,53274216,https://www.airbnb.com/users/show/53274216,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
34,62015,https://www.airbnb.com/rooms/62015,20220605131734,2022-06-05,"Charming, beautifully & sunny place with cat Luna",This beautiful apartment in one of the most li...,In this neighborhood is a lot to do: lots of c...,https://a0.muscache.com/pictures/e6cb417b-6d76...,301340,https://www.airbnb.com/users/show/301340,...,4.94,4.68,4.59,0363 B090 499C D757 7F4F,f,1,1,0,0,0.26

In [52]:
data[data['description'].str.contains(' cat ')].loc[17]['description']

'Nice 2 bedrome flat on the ground floor in peaceful neghbourhoos. Garden with trampoline and garden couch. Close to public transport, canal for swimming, basketball and football field, playgrounds and skateboard park. Perfect for families. 2 skateboards and protection available for your use for children. We prefer longtime renters, that will care for our cat as well, therefore reduced price.'

#### Filtrar usando m√°s de una condici√≥n
Supongamos que ahora queremos ver los listings con buenas puntuaciones pero ademas que tengan m√°s de 2 habitaciones

In [53]:
data[(data['review_scores_rating']>4)&(data['bedrooms']>4)].head()

,id,listing_url,scrape_id,last_scraped,name,description,neighborhood_overview,picture_url,host_id,host_url,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
59,283170,https://www.airbnb.com/rooms/283170,20220605131734,2022-06-05,5-bedrooms house; central location,The apartment is a modern five bedroom apartme...,NaN,https://a0.muscache.com/pictures/4930015/6940b...,1451657,https://www.airbnb.com/users/show/1451657,...,4.83,4.71,4.14,0363 0240 34A0 48C3 6D81,f,1,1,0,0,0.91
67,307497,https://www.airbnb.com/rooms/307497,20220605131734,2022-06-05,Sailing ship group stays in Amsterdam,Welcome on board of our historical sailing shi...,Amsterdam,https://a0.muscache.com/pictures/4767012/c9537...,1582128,https://www.airbnb.com/users/show/1582128,...,4.87,4.56,4.53,Exempt,f,2,2,0,0,0.85
160,742160,https://www.airbnb.com/rooms/742160,20220605131734,2022-06-05,Sailing ship group stays in Amsterdam,Welcome on board of our historical sailing shi...,NaN,https://a0.muscache.com/pictures/10197815/6503...,1582128,https://www.airbnb.com/users/show/1582128,...,4.89,4.51,4.59,Exempt,f,2,2,0,0,0.99
202,874688,https://www.airbnb.com/rooms/874688,20220605131734,2022-06-05,5 BR apartment / Quiet / Garden,5 BR contemporary apartment on a beautiful can...,NaN,https://a0.muscache.com/pictures/12850370/192a...,4585922,https://www.airbnb.com/users/show/4585922,...,4.96,4.80,4.36,0363 7FD9 A20B AF5B 0687,f,1,1,0,0,0.26
220,934060,https://www.airbnb.com/rooms/934060,20220605131734,2022-06-05,"LOTUS, Classic Dutch Saling Barge",Staying on our sailing ship is a truly unique ...,The former NDSM Amsterdam ship wharf is a stun...,https://a0.muscache.com/pictures/2dec5f9f-e56b...,5037506,https://www.airbnb.com/users/show/5037506,...,4.88,4.30,4.63,Exempt,f,2,0,2,0,1.20

### Filtrar usando una isnull(), notnull()
Muchas veces queremos saber si alguna variable tiene datos nulos.

In [54]:
data[data['host_neighbourhood'].isnull()][['host_neighbourhood']].head()

  host_neighbourhood
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN

In [55]:
data[data['host_neighbourhood'].notnull()][['host_neighbourhood']].head()

     host_neighbourhood
24       Indische Buurt
25       Grachtengordel
26  Westelijke Eilanden
27    Amsterdam Centrum
28    Amsterdam Centrum

### Duplicated, Sort, Unique
Supongamos que no queremos tener valores rerpetidos de listings. 
1. Vamos a fijarnos si tenemos valores repetidos. Eso lo podemos hacer con el m√©todo `.duplicated`

In [57]:
data[data['listing_url'].duplicated(keep = 'first')]

Empty DataFrame
Columns: [id, listing_url, scrape_id, last_scraped, name, description, neighborhood_overview, picture_url, host_id, host_url, host_name, host_since, host_location, host_about, host_response_time, host_response_rate, host_acceptance_rate, host_is_superhost, host_thumbnail_url, host_picture_url, host_neighbourhood, host_listings_count, host_total_listings_count, host_verifications, host_has_profile_pic, host_identity_verified, neighbourhood, neighbourhood_cleansed, neighbourhood_group_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities, price, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, calendar_updated, has_availability, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, first_review, last_review, review_scores_rating, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, license, instant_bookable, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month]
Index: []

[0 rows x 74 columns]

Por lo que vemos arriba, en este dataset no hay listings repetidos. 

Se ve que lo limpiaron bien üßπüßπüßπüßπüßπüßπ

Supongamos solo queremos tener un listing por `host_id` para poder calcular `host_total_listings_count` medio de esta ciudad

In [58]:
data[~(data['host_id'].duplicated(keep = 'last'))]['host_total_listings_count'].mean()

1.984950495049505

In [59]:
# Chequeamos que la longitud del dataframe resultante sea la misma que la cantidad de host_ids unicos
len(data[~(data['host_id'].duplicated(keep = 'last'))]), len(data['host_id'].unique())

(5050, 5050)

In [60]:
data[~(data['host_id'].duplicated(keep = 'last'))]['host_total_listings_count'].median()

1.0

Ahora supongamos que queremos quedarnos con un √∫nico registro por host pero quedarnos solo con aquel registro que tiene la mayor cantidad de `bedrooms`. Entonces, primero, ordenamos los datos y luego los filtramos con `duplicated`

In [61]:
data.sort_values(by = 'bedrooms', inplace = True, ascending = False)

In [63]:
# luego, miremos cuales son os host_ids que estan duplicados para tener una idea
data[data['host_id'].duplicated(keep = False)]['host_id']

1277     18081564
67        1582128
2371     22879651
3149      5037506
160       1582128
          ...
6140    214764531
6143    214764531
6161    384216171
6166    384216171
6168    384216171
Name: host_id, Length: 1667, dtype: int64

In [64]:
# miramos un ejemplo en particular
data[data['host_id'] == 4271294][['bedrooms']]

      bedrooms
3531       2.0
4050       1.0
3689       1.0

In [65]:
data[(~(data['host_id'].duplicated(keep = 'first')))&(data['host_id']==4271294)][['bedrooms']]

      bedrooms
3531       2.0

## Tipos de datos
Como ya se habr√°n dado cuenta, los datos dentro de las Series y los DFs tiene un tipo de dato ü§∑
Los datos puede ser de cualquier tipo y los podemos pasar de un tipo de dato a otro. 

Abajo vemos que el id es un n√∫mero.  Muchas veces, resulta √∫til guardar los ids como strings. Esto lo podemos hacer con el m√©todo `astype`

In [66]:
data['id'].head(5).tolist()

[9990099, 307497, 20840176, 29874862, 742160]

In [67]:
data['id'] = data['id'].astype('str')

In [68]:
data['id'].head(5).tolist()

['9990099', '307497', '20840176', '29874862', '742160']

Tambi√©n es √∫til definir el tipo de dato cuando leemos el archivo para evitar p√©rdidas de informaci√≥n. Por ejemplo, supongamos que tenemos un id que empieza con ceros, 000034. 
Cuando pandas lea ese dato, si no le decimos que es una string, lo va a leer como un n√∫mero y vamos a perder los 0000.

Para definir el tipo de dato podemos hacer lo siguiente:

In [69]:
data = pd.read_csv('listings.csv.gz', dtype = {'id':'str'})

In [71]:
data.id.tolist()[:10]

['23726706',
 '35815036',
 '31553121',
 '34745823',
 '44586947',
 '15801253',
 '19572024',
 '18801518',
 '2973384',
 '34985473']

### Ejercicios:
Descargar el archivo de distribuci√≥n de empleo formal en el AMBA de este [link](https://www.datos.gob.ar/dataset/produccion-distribucion-empleo-formal-amba) (el que en su t√≠tulo dice hasta CLAE2)
1.   Calcular la cantidad de departamentos y sectores (CLAE 2 d√≠gitos) qu√© emplean:

  1.   solo hombres
  2.   solo mujeres
  3.   a ambos g√©neros
  4.   pensar una estrategia para chequear que los datos son "buenos"

2. Calcular la remuneraci√≥n media para hombres y para mujeres
3. Calcular la remuneraci√≥n media para mujeres en el CLAE = 6

Nota: realizar consideraci√≥n acerca del promedio de promedios